### PR TITLE
checked if reason of feedback is spam

### PR DESCRIPTION
**Pull request by ayush3298**
feedback required message can be recived by some other reasons also, so checking if spam

### CODE REVIEW

**Review by maxdevblock — CHANGES_REQUESTED** [review]
Should be
...`and response_data.get('spam') and response_data['spam'] == True`

**Comment by maxdevblock** [comment]
> feedback required message can be recived by some other reasons also, so checking if spam

You're right but, as you said, you can receive `feedback_required` for many reasons, not only for spam. If you get `feedback_required` and you don't give up with that action, your account could be blocked or even deleted, even if the reason of `feedback_required` is not spam...

**Comment by ayush3298** [comment]
"comments_disabled": true,
    "feedback_ignore_label": "OK",
    "feedback_message": "redhead.speaks has turned off comments for this post.",
    "feedback_required": true,
    "feedback_title": "Commenting is Off",
    "message": "feedback_required",
    "status": "fail"
}
Here the comment was disabled, so it won't be good to not comment on other media's because one is disabled.

**Comment by ayush3298** [comment]
have made the required changes

**Comment by ohld** [comment]
@maxdevblock can it be merged now?

**Comment by maxdevblock** [comment]
> @maxdevblock can it be merged now?

Yes I think it's ok now

**Review by maxdevblock — DISMISSED** [review]

**Comment by maxdevblock** [comment]
Should be
`and response_data['spam']`
not
`and response_data['spam'] == True`

**Comment by ayush3298** [comment]
sorry for this, have updated the changes

**Comment by ohld** [comment]
Please fix Travis CI error.

**Comment by ohld** [comment]
@ayush3298 `FileNotFound` - variable not found. Please fix the issue.

**Comment by ayush3298** [comment]
@ohld sorry but I can't understand it, its running fine on my machine. Can you please help me a little?

**Comment by ohld** [comment]
Take a look into a Travis logs: https://travis-ci.org/instagrambot/instabot/jobs/491645538

**Pull request closed without merging**
