### PR TITLE
Add get_thread function

### PR DESCRIPTION
**Pull request by Limule**
Add get_thread function which come from the original php api

### CODE REVIEW

**Comment by ohld** [comment]
Awesome! Thank you for your great work! May I ask you to add more endpoints, please? For instance, we really need someone to fix the upload media endpoint

**Review by ohld — APPROVED** [review]

**Comment by Limule** [comment]
Where can I find more endpoints ?

**Comment by ohld** [comment]
I’d suggest you to check JavaScript and PHP Instagram private API wrappers. The last one is the best in my opinion.

**Comment by ohld** [comment]
https://github.com/mgp25/Instagram-API

**Pull request merged**
