### PR TITLE
Unfollow users followed more than X seconds ago

### PR DESCRIPTION
**Pull request by alex-grover**
Hello, another one from me!

I implemented the feature described in the title. This exists in other libraries that I've seen, and it's really nice for a few reasons:

1. You don't have to whitelist everyone you're already following before starting to unfollow users, the bot can keep track of that internally
2. It enables you to unfollow people after a certain amount of time. That way you don't have to manually choose when to unfollow users based on when you think they would have seen the follow notification.

To do this, I used `sqlite` because the current system of tracking follows/unfollows in a text file doesn't easily allow you to add and query things like `followed_at` time. It would be possible to do it by using something more similar to a CSV file but in my opinion using a database is the way to go! It might be a bit more opaque for the non tech-savvy users but it allows you to record a lot more information about what the bot is doing.

A few open questions remain:
- [ ] It seems like there's a bug with `check_user` for unfollowing. it is a bit difficult for me to understand everything that method is trying to do for unfollows, but when I was writing the test it seems like the `unfollow` method exits early because `check_user` just makes it to the end of the method and returns `True`. I can write a simple failing test if that explanation was confusing :)
- [ ] Do I need to support multiple accounts being run on the same machine? It doesn't seem like the bot does in general but just want to make sure.

The expected usage of this feature:
```python
import os

from dotenv import load_dotenv
from instabot import Bot


THREE_DAYS_IN_SECONDS = 3 * 24 * 60 * 60


load_dotenv()

username = os.getenv('USERNAME')
password = os.getenv('PASSWORD')
proxy = os.getenv('PROXY')
target_accounts = os.getenv('TARGET_ACCOUNTS').split(',')
follows_per_account = int(os.getenv('FOLLOWS_PER_ACCOUNT'))


bot = Bot()
bot.login(username=username, password=password, proxy=proxy)

for account in target_accounts:
    bot.follow_followers(account, follows_per_account)

# Unfollows users the bot followed more than 3 days ago
bot.unfollow_after(THREE_DAYS_IN_SECONDS)
```

Thanks for reading, let me know if I can clarify anything!

### CODE REVIEW

**Comment by ohld** [comment]
hmm, this looks promising. 

One of the idea that I had is to create a webserver-like (maybe docker image) that just inputs the Instagram username and password and can accept any requests via http (`flask` or `django` may help there). 

So we can just the 'instabot daemon' and sent the requests like 'like this media_id' or 'get followers of user_id'. As a result, we can combine these 'nodes' into a swarm and manipulate lots of the accounts from one admin panel.

Users could just run their 'node' in Heroku and control it via some admin panel. (by the way, the control panel for only one account may be run on the same node which receives https request! we would need the separate admin panel only to control several bots).

And all these nodes will definitely have their own database inside (to cache Instagram responses for example).

What do you think? Can we create this thing instead of fixing real buggy instabot?

**Comment by ohld** [comment]
Also, we can create a test Instagram account to run tests on it using Travis-CI secret environment variables: we commit - the test account perform some real actions in Instagram to test the functionality. Huh? 🥇

**Comment by alex-grover** [comment]
oops, i just copy/pasted from the other test, must have been my mistake with the requests 😅

that does sound cool, but i think it's a bit of overkill for my use case. personally, I just want to set up a server that does follow/unfollow and some likes on a daily basis via `cron`. an admin interface would definitely be nice to have but it's not a hard requirement for me. and i'm only controlling one account at the moment!

**Review by ohld — DISMISSED** [review]

**Review by ohld — APPROVED** [review]

**Comment by alex-grover** [comment]
After thinking about this a bit more, I'm gonna hold off on merging this. I'm a little worried about the changes to `check_user` and it doesn't seem like there are any other users requesting this specific behavior, so I'm just going to use it from my fork for the time being.

**Comment by ohld** [comment]
Great solution! I'd suggest committing overall bugfixes and improvements anyway.

**Comment by maxsonic** [comment]
@ajgrover would you mind sharing your fork? i think this feature is a must..

**Comment by alex-grover** [comment]
I deleted it but you can pull the diff from here! Sorry about that

**Pull request closed without merging**
