### PR TITLE
Download multiple photos included by a post

### PR DESCRIPTION
**Pull request by abcdefgs0324**
Hi, I am new to this repository.
Users can include multiple photos in a post, mentioned in #78 , and I want to fix that we can't download all multiple photos in a post.
I'm not sure which return value is better if there are multiple photos in a post, a list or the path of the first/last photo.
Any suggestion is appreciated. Thanks.

### CODE REVIEW

**Comment by ohld** [comment]
@sudoguy @basnijholt Can somebody check this?

**Review by basnijholt — DISMISSED** [review]
LGTM!

**Comment by ohld** [comment]
@abcdefgs0324 Please rebase and add tests and example script for your code.

**Comment by abcdefgs0324** [comment]
@ohld Okay, I will try to do it in a few days.

**Comment by ohld** [comment]
@abcdefgs0324 any updates?

**Review by sudoguy — APPROVED** [review]

**Comment by sudoguy** [comment]
@abcdefgs0324 Thanks a lot! 👍

**Comment by ohld** [comment]
Great job!

**Pull request merged**
