### PR TITLE
Opening comments file using UTF-8

### PR DESCRIPTION
**Pull request by EightShift**
Opening comments file using UTF-8 to commenting with emoji on windows.

### CODE REVIEW

**Comment by ohld** [comment]
Can you guys please check that this solution works fine on Mac OS and Linux.

**Comment by EightShift** [comment]
@ohld I don't understand why Python 2.7 is failed check...

**Comment by ohld** [comment]
You can read the logs. Python2.7 have different `open` function with different arguments.

**Comment by ohld** [comment]
You can read the logs. Python2.7 have different `open` function with different arguments.
https://travis-ci.org/instagrambot/instabot/jobs/541124029#L648

**Comment by ohld** [comment]
Please update branch to pass Travis-CI

**Pull request closed without merging**
