### PR TITLE
auto posting of pictures from the folder

### PR DESCRIPTION
**Pull request by ppleskov**
- script posts one picture per day from folder ./pics (timeout can be adjusted)
- pic name should be in the following format: "# Post caption text.jpg"
- Number and .jpg will be amended in the post caption
- file pics.txt is required in the root folder (to store posted pictures)

### CODE REVIEW

**Comment by ohld** [comment]
Create a **folder** for your example, create **pics/ folder** and put **example image** and **pics.txt** file. Also create an Readme.md with all instructions how to use your example.

**Comment by rasperepodvipodvert** [comment]
you will make schedule for posting picthures?
Title include in pics.txt first line

for example:
-./pics
--17.03.01
---pics.txt
---pics.jpg
--17.03.02
---pics.txt
---pics.jpg

it is very used function!!!

**Comment by ppleskov** [comment]
schedule is already there:
- order is set by names of the files, like "1 Sunset.jpg", "2 Waterfall.jpg", "3 Desert.jpg", etc.
- frequency is set by timeout (one pic per day in the example)

**Comment by rasperepodvipodvert** [comment]
may be example code post?

**Comment by ppleskov** [comment]
added folder

**Comment by ppleskov** [comment]
added readme

**Comment by lameei** [comment]
The method used for the caption is not suitable for long ones. Is it possible to read captions from a file and upload them?

**Comment by ohld** [comment]
@sudoguy Can you please answer @lameei question?

**Comment by lameei** [comment]
@sudoguy @ohld I have made some changes to auto_post.py and now the captions are loaded from text files. User needs to obey from this naming convention which the name of the files should get started by numbers so the caption of "1 First pic.jpg" will be inside "1 caption.txt". The name of the files are not important but the numbers are. 

```
import time
import sys
import os
import yaml
import glob

sys.path.append(os.path.join(sys.path[0], '../../'))
from instabot import Bot

posted_pic_list = []
try:
    with open('pics.txt', 'r') as f:
        posted_pic_list = f.read().splitlines()
except:
    posted_pic_list = []

timeout = 24 * 60 * 60 

bot = Bot()
bot.login()

while True:
    pics = glob.glob("./pics/*.jpg")
    pics = sorted(pics)
    try:
        for pic in pics:
            if pic in posted_pic_list:
                continue

            path = "./pics"
            for root, dirs, files in os.walk(path):
                jpgs =[]
                texts=[]
                for name in sorted(files):
                    if name.endswith(".jpg"):
                        jpgs.append(name)
                    if name.endswith(".txt"):
                        with open(path +"/" + name, "r") as caption_file:
                            caption = caption_file.read()
                            texts.append(caption)

                for i in range(0,len(jpgs)):
                    print("upload: " + texts[i])
                    mypic = path + "/"+jpgs[i]
                    bot.uploadPhoto(mypic, caption=texts[i])
                    if bot.LastResponse.status_code != 200:
                        print(bot.LastResponse)
                        # snd msg
                        break

                    if not pic in posted_pic_list:
                        posted_pic_list.append(pic)
                        with open('pics.txt', 'a') as f:
                            f.write(pic + "\n")

            time.sleep(timeout)

    except Exception as e:
        print(str(e))
    time.sleep(60)
```

**Pull request merged**
