### PR TITLE
follow_users sleep for 5 minutes when got 400 error

### PR DESCRIPTION
**Pull request by wanlorn75**
I'm trying to fix this because I want the bot stop when instagram block follow requests.

### CODE REVIEW

**Comment by ohld** [comment]
Why don't you want just to sleep for a long time? Like 5minutes

**Comment by wanlorn75** [comment]
one of my accounts is blocked just after login at the first attempt to follow someone. I just want to prevent to loose the account.
I'm doing some test and the change I made is not solving the problem like i was hoping.
I can't separate the error 400 for blocking the follow from the error 400 for challange required.

**Comment by wanlorn75** [comment]
> Why don't you want just to sleep for a long time? Like 5minutes

maybe sleep for 5 or 10 minute can be a solution for someone. If you thing can be usefull I can modify the pull request. :)

**Comment by ohld** [comment]
Yep, I think that this would be useful:
print that you are going to sleep for 5 minues and then sleep

**Comment by ohld** [comment]
Also fix the travis issues please

**Comment by wanlorn75** [comment]
ok done, checks are ok now :)

**Comment by doctornuclear** [comment]
I don't think it is worth to add 5 min sleep rather than break the loop because the block persists more than 5 minutes and it not worth it to keep making the bot sleep

**Comment by hosnas** [comment]
how can we do this for direct message bot?

**Comment by steffanjensen** [comment]
I have seen a pattern, if the bot makes a requests when the "action is blocked" then the timer for the action blocked will become longer, it's very important that the sleeping around the "block" outputs are long. Around 5-10+ min. 

For example: 
If the action is blocked for 5 min and you make two-ten requests while blocked then i looks like it will just become 10-30 min blocked.. If the sleep between blocked happens, then i get out of the blocked action, if i keep sending requests, then i am blocked for as long as the bot are running + extra hours. 

I have only tested the with a few functions, so i don't know if it works on "likes/comments" also.

**Comment by ohld** [comment]
hmm, to be honest, I don't know how would be better: to sleep or to exit if 400 error.

let's vote with emoji! Press **rocket** for sleep and **eyes** for exit.

**Comment by AKwoKWH** [comment]
Dont we already have the action block protection which do not "like" anymore if instagram return 400 error.

Do you mean the action block protect only activate when we have the 2nd attempt of "like" failed?
aka:

1  - try to like a pic
2  - return a 400 error
3  - do NOT activate action block protection and wait 5 min 
4  - try again to like the pic
5a- 400 error again => activate action block protection 
5b- success => continue

**Comment by ohld** [comment]
So the poll results are a draw - we can't choose what is better - results are almost identical

**Pull request closed without merging**
