### PR TITLE
feature-method-get-latest-media-with-count

### PR DESCRIPTION
**Pull request by mstikharev**
Added the **feature** to get the **N** count of the last posts of the user on the **_user_id_** and **_count_** params.
Usage:
`get_last_user_medias(user_id=0, count=3) `

Return an array of posts id
Example:
`[12345,5677,12312]`

### CODE REVIEW

**Comment by basnijholt** [comment]
Great job!

Could you change `count` -> `amount`?

and we can simplify the code by changing `get_total_user_feed` to 
```python
def get_total_user_feed(self, user_id, min_timestamp=None):
    return self.get_last_user_feed(user_id, amount=float('inf'), min_timestamp=None)
```
could you add that too? :)

**Comment by mstikharev** [comment]
I believe that users should use two methods, one for parsing all posts, an arc for parsing a certain number of posts. I can fix the code if this is more correct.

**Comment by basnijholt** [comment]
I am not sure what you mean exactly. Could you elaborate a bit? :)

**Comment by mstikharev** [comment]
Oops, my bad 😄 I did not know what float('inf) means. I'll fix in near future.

**Comment by basnijholt** [comment]
Thanks for the changes!

I actually meant that you change https://github.com/MaxStik/instabot/blob/ea26b46d347bca08b822e70331daf7feed68b779/instabot/api/api.py#L602 instead of the bot method.

I've changed it now :)

**Review by basnijholt — APPROVED** [review]

**Comment by basnijholt** [comment]
Thanks for your contribution! 👍

**Pull request merged**
