### PR TITLE
fix file not being found

### PR DESCRIPTION
**Pull request by bruvv**
not sure if this is the same in other files, just started using the bot.

### CODE REVIEW

**Review by ohld — DISMISSED** [review]

**Comment by ohld** [comment]
Great fix! Please fix also all Travis-CI issues - and I'll merge this PR!

**Comment by bruvv** [comment]
I don't know how Travis works

**Comment by ohld** [comment]
image

you can press "Details" to find all codestyle issues


https://travis-ci.org/instagrambot/instabot/builds/630433160?utm_source=github_status&utm_medium=notification

**Comment by bruvv** [comment]
I know. It's already mentioned in my first post... The file check I added is working but failing for the bot because the file is missing and I do not know how to add the file.

**Comment by bruvv** [comment]
Totally missed the random import! Fixed :)

**Comment by bruvv** [comment]
Also changed it a bit, pick a random user and get the best photo from that user and post only 1 photo. no need to pick all the accounts and waste a lot of requests

**Comment by ohld** [comment]
Great, thanks! But seems that Travis still fails. Can you please check the issues and fix them again, sorry.

**Comment by bruvv** [comment]
Weird. Had some stuff commented that failed Travis to build it. Removed those comments and now it's passing.

**Review by ohld — APPROVED** [review]

**Comment by ohld** [comment]
Thanks!

**Pull request merged**
