### PR TITLE
Fix for issue #756

### PR DESCRIPTION
**Pull request by barclaey**

### CODE REVIEW

**Comment by maxdevblock** [comment]
Change
`return self.send_request(url)`
to
`return self.send_request(url, '')`

**Comment by maxdevblock** [comment]
> Change
> `return self.send_request(url)`
> to
> `return self.send_request(url, '')`

Made other tests.
This makes Travis pass the test but returns 405 error anyhow.
The solution was that one you suggested, but need to fix the tests too.

**Comment by maxdevblock** [comment]
@barclaey 
Need to edit tests too
in tests/test_bot_get.py
`test_get_media_info`
`test_get_media_owner`
calls are still POST, need to be GET, or Travis will fali

**Comment by ohld** [comment]
There are two pull requests now. Which one solves the problem and should be merged?

**Comment by maxdevblock** [comment]
Got the fix for tests (from POST to GET), sending pull request

> There are two pull requests now. Which one solves the problem and should be merged?

This one has got the solution for _api.py_ but Travis fails with this because in tests the calls are still POST.
In the other one #758 I fixed the tests too.

**Comment by ohld** [comment]
Ok, I'll close this PR and will merge yours, right?

**Comment by maxdevblock** [comment]
> Ok, I'll close this PR and will merge yours, right?

Right. Thanks to @barclaey to have solved the issue!

**Comment by ohld** [comment]
@barclaey Thank you for your help

**Pull request closed without merging**
