### PR TITLE
Feature/flake8 errors

### PR DESCRIPTION
**Pull request by nikolasvargas**
Hello. To start my contribution with the instabot project, I fixed all flake8 errors, first.
- fixed all flake8 errors in the project
- updated flake8 pre-commit rules

### CODE REVIEW

**Comment by ohld** [comment]
Thank you very much! Looks great! Please check my comment

**Comment by basnijholt** [comment]
Did you actually run `pre-commit run --all` and it succeeds?

**Comment by ohld** [comment]
@basnijholt I removed pre-commit from deployment more than a month ago, because it makes the development process not straightforward and non-universal but project-specific. We've discussed it already.

**Comment by ohld** [comment]
@nikolasvargas Thanks for the contribution again. I'll merge it soon.

**Comment by basnijholt** [comment]
@ohld, that is not what I mean, CI and `pre-commit` are two independent parts.

One can just run `pre-commit run --all` and run all the checks.

**Comment by ohld** [comment]
@basnijholt Yes, but how does it correlate with the content of that pull request? Why have you closed it?

**Review by ohld — APPROVED** [review]

**Comment by basnijholt** [comment]
Oops, sorry! I accidentally closed it. 

The changes are in style and the rules are guided by the pre-commit config.

**Comment by ohld** [comment]
@basnijholt I think that these rules should be automatically checked also in the CI pipeline to prevent the appearance of unstyled code in the master branch.

**Comment by ohld** [comment]
One of the main ideas of CI is to check code style automatically without asking contributors to run any additional commands. Yes, you can use `pre-commit`, but the code style should be checked in CI in any way.

**Pull request merged**
