### PR TITLE
keep increasing the timeout if we get soft banned

### PR DESCRIPTION
**Pull request by bruvv**

### CODE REVIEW

**Comment by ohld** [comment]
Right now we have a ton of parameters if Bot class. And all of them are undocumented. I'd suggest writing comments to help others to understand what this param is about. And make the name longer and more descriptive (like sleep_time_bad_response).

Also Increasing the sleep time by 5 minutes is not good approach, I'd suggest += 1 minutes.

**Comment by bruvv** [comment]
Done, why not use 5 minutes? I suggest 5 minutes since it is a bot and I have it running 24/7 so for long task it should be very careful with instagram and there bot spotting approaches. Just adding 1 minute will mean we hit that 429 error a lot more.

But I understand if you want to run the bot quickly 1 minute is a better approach, so I did change it.

**Comment by ohld** [comment]
I also suggest renaming the variable from `sleep_minutes` to something more clearer and longer. Imagine yourself as a new user trying to understand something about this param and what it does.

**Comment by bruvv** [comment]
Changed it

**Review by ohld — APPROVED** [review]

**Comment by ohld** [comment]
Thanks!

**Pull request merged**
