### PR TITLE
fix get_user_reel and get _users_reel to return items of reels

### PR DESCRIPTION
**Pull request by elmissouri16**
I tweak this 2 functions to return items of reels to be able to add to the see_reels function 
this is a fix for #929 
solution provided by @heyt0ny

### CODE REVIEW

**Comment by ohld** [comment]
I don't think that the function `get_users_reels` should be changed: it returns the data in the format that was received from instagram. I'd suggest changing the `see_reels` function to be able to accept the input in dictionary format.

**Comment by elmissouri16** [comment]
> 
> 
> I don't think that the function `get_users_reels` should be changed: it returns the data in the format that was received from instagram. I'd suggest changing the `see_reels` function to be able to accept the input in dictionary format.

thats make sense when I get time I well try implement thats

**Comment by elmissouri16** [comment]
@ohld  can you review this

**Comment by ohld** [comment]
The review was given, no changes have been given from your side too.

**Comment by elmissouri16** [comment]
> 
> 
> The review was given, no changes have been given from your side too.
 i commit it 7 days ago [https://github.com/instagrambot/instabot/pull/944/commits/955abb00d608fcebe7061e2ac5c93e63c8a642c7](url)

**Comment by ohld** [comment]
https://github.com/instagrambot/instabot/pull/944/files

**Comment by elmissouri16** [comment]
sorry but I'm closing this for now because i don't know much about git and how to fix this conflict I well open when i know how

**Pull request closed without merging**
