### PR TITLE
Interactive two-factor authentication workaround

### PR DESCRIPTION
**Pull request by skareemoff**
I know this is not a proper automated solution. Having said that, I hope this will help people resolve most of their needs by entering the code manually when launching the bot.

### CODE REVIEW

**Comment by ohld** [comment]
Thanks for your pull request! Can you please fix all Travis-CI issues before merging? Thanks. The list can be found right here above.

**Comment by ohld** [comment]
By the way, I want to really thank you for your contribution. We will use your code in our web tool too:https://github.com/instagrambot/web

**Comment by skareemoff** [comment]
> By the way, I want to really thank you for your contribution. We will use your code in our web tool too:https://github.com/instagrambot/web

No worries at all. Thank you for the wonderful tool!

**Comment by skareemoff** [comment]
> Thanks for your pull request! Can you please fix all Travis-CI issues before merging? Thanks. The list can be found right here above.

I am fairly new to using GIT. I just realised that I created a pull request from the HEAD of my fork. I created a branch and fixed the tests there. 
How can I switch the pull request to the branch now? Or should I create a new pull request?

**Comment by skareemoff** [comment]
Looks like it is not possible to switch, so I created a branch and a new pull request. Tests are passing there now.

**Pull request closed without merging**
