### PR TITLE
Added example + refactored ultimate_schedule

### PR DESCRIPTION
**Pull request by El3k0n**
- Added a script to download some user's photos
- Refactored/Updated ultimate_schedule: all changes are described in the corresponding commit.

### CODE REVIEW

**Comment by onkaraman** [comment]
Can you confirm that this works?

01 Go to app or instagram.com and change password.
02 Try successfully logging in with this library.

**Comment by El3k0n** [comment]
I'm not sure I understand what you mean. If you change your account's password and try to login with instabot the login is unsuccessful because the bot saves your credentials in secret.txt in the form username:password. If you change your Instagram password, the file secret.txt doesn't automatically update, which means the bot will try to login with a wrong password.
The bot does this "by design": you should pay attention when changing your password, and update it on your instance of instabot. Moreover, it has nothing to do with my pull request.

**Comment by onkaraman** [comment]
I know that. Did you try it on yourself though?
Can you change your pass and access from the bot after that?

I am asking to find out where this started.

**Comment by El3k0n** [comment]
I just tried and can confirm that it works as expected. I even tried not updating secret.txt: the first time you try to login with an incorrect password (old secret.txt) the bot gives you an error, exits, and deletes the old secret.txt. Then when you try again it creates a new secret.txt with the new password.

What do you mean with "where this started"?

**Comment by onkaraman** [comment]
Whenever I try to login I get

```
2017-12-09 01:07:30,632 - INFO - Instabot Started
2017-12-09 01:07:33,789 - ERROR - Request return 400 error!
2017-12-09 01:07:33,789 - INFO - Instagram error message: challenge_required
2017-12-09 01:07:33,789 - INFO - Error type: checkpoint_challenge_required
2017-12-09 01:07:33,789 - INFO - Login or password is incorrect.
```

And although I accept the challenge on instagram.com, it still errors after that.

**Comment by El3k0n** [comment]
I don't understand why you're writing all this here. If you downloaded instabot from the official repo, you didn't download MY code, as this pull request is still open. If you have any problem trying to login with instabot, this is not the right place to discuss it. Try opening an issue on the official repo and see if somebody can help you out.

**Comment by ohld** [comment]
@El3k0n Have you tested your code?
@onkaraman Please, download the code from this pull request, delete local copy of instabot with `pip uninstall instabot` and then try to launch the script again. If it works, answer here, please.

**Comment by El3k0n** [comment]
@ohld I tested the code multiple times. Honestly I have no reason to think @onkaraman is even using this code. Why would he download code from a pull request instead of downloading from the official repo?

**Comment by onkaraman** [comment]
@El3k0n You are right. When I asked you about the error I knew that it didn't concern your pull request. I talked to you because I saw you as a capable developer and expected some help in problem solving. 

You in fact helped me a lot with your analysis so I am thankful, anyway.

And thanks for contributing!

**Pull request merged**
