### PR TITLE
Added tag feature in photo and story upload

### PR DESCRIPTION
**Pull request by thehelvijs**
### Uploading photo with tag / mention:
```python
users_to_tag = [
	{'user_id': user_id_1, 'x': 0.5, 'y': 0.1},
	{'user_id': user_id_2, 'x': 0.5, 'y': 0.5}
]
bot.upload_photo(image, user_tags = users_to_tag, caption = caption)
```

### Uploading stories with tag / mention:
```python
users_to_tag = [
	{'user_id': user_id_1, 'x': 0.5, 'y': 0.1, 'width': 0.79, 'height': 0.21, 'rotation': 0.0},
	{'user_id': user_id_2, 'x': 0.5, 'y': 0.5, 'width': 0.79, 'height': 0.21, 'rotation': 0.0}
]
bot.upload_story_photo(image, user_tags = users_to_tag)
```

### TO DO:

- Function for generating _users_to_tag_ list by entering **username** instead of **user_id** and **position** instead of **x** and **y** e.g. process_user_tags(username, 'top_left'). There could be issue with multiple tags, so maybe make function that takes **user_list** as argument:
```python
user_list = [
	{'username': 'username1', 'position': 'top_left'}
	{'username': 'username2', 'position': 'center'}
]
process_user_tags(user_list)
```
Or perhaps just hard-define positions and once multiple usernames are added, these positions are taken one by one.
- Story tag is invisible and only comes visible when clicked, therefore some overlay text has to be added over the image before posting (_using Pillow?_) e.g. '@username' . This could be added to _stories_shaper_ function in _api_photo.py_.

[Private Instagram API](https://github.com/ping/instagram_private_api/blob/f36e217f6f252a611e55d47aff1ac4309ac7f3a1/instagram_private_api/endpoints/media.py) was used as reference for JSON formatting.

_BTW, this is my first pull request.. ever.._

### CODE REVIEW

**Comment by ohld** [comment]
Wow! Great update! Thanks a lot! May I ask you to create the pull request to our instabot2.0 branch? https://github.com/instagrambot/instabot/pull/1008 #1008 
It would be a really nice feature to be added into instabot2.0

**Comment by ohld** [comment]
@maxdevblock May I ask you to support with the Pull request? I really want this to be in instabot2.0 release, but the pull request also requires the CI code style refactoring and making the "user_tags" param optional.

**Comment by maxdevblock** [comment]
> @maxdevblock May I ask you to support with the Pull request? I really want this to be in instabot2.0 release, but the pull request also requires the CI code style refactoring and making the "user_tags" param optional.

Ok, I take a look :-)

**Comment by ohld** [comment]
@tkd-alex

**Comment by ohld** [comment]
@tkd-alex - can you please merge this to your #1008 branch? Thanks

**Comment by jerryan9999** [comment]
"This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake"

**Pull request closed without merging**
