### PR TITLE
Solve `checkpoint_challenge_required` login errors

### PR DESCRIPTION
**Pull request by alex-grover**
I took a stab at integrating the code provided in issue #630. It was easiest just to add it into the `API` class, although I think that it would make sense to extract it into a module of its own if possible for clarity. The code is mostly just copy/pasted from the issue but I'm happy to get this ready to merge if you're interested.

There are no tests written yet but it works (manually tested) with the following code:

```python
import os

from dotenv import load_dotenv
from instabot import Bot


load_dotenv()

username = os.getenv('USERNAME')
password = os.getenv('PASSWORD')
proxy = os.getenv('PROXY')
target_accounts = os.getenv('TARGET_ACCOUNTS').split(',')
follows_per_account = int(os.getenv('FOLLOWS_PER_ACCOUNT'))


bot = Bot()
bot.login(username=username, password=password, proxy=proxy)

for account in target_accounts:
    bot.follow_followers(account, follows_per_account)
```

I also set up Pipenv and added a couple lines in `CONTRIBUTING.md` to help people get the repo set up as it wasn't immediately clear. If that's unwanted I can remove the commit before merging.

### CODE REVIEW

**Comment by ohld** [comment]
Great pull request! Thanks! 
May I ask you to fix Travis-CI issues first, then I'll merge

**Comment by ohld** [comment]
Just simple stuff:
image

**Comment by alex-grover** [comment]
All done, that line is kinda long now since the linter complains either way you put the operators haha. 

Just want to double check that you're ok with the change to the packaging tools before you merge - it might affect the other contributors!

**Review by ohld — APPROVED** [review]

**Comment by ohld** [comment]
Thanks for your work! Can't wait for your next fixes and improvements in this working piece of shitcode called Instabot. Your packaging change looks right.

**Pull request merged**
