### PR TITLE
fixing bot_like_feed to handle data from feed that has no pk values, …

### PR DESCRIPTION
**Pull request by DrCherry**
…in this case suggestions.

Right in the middle of the media feed is a "suggestions" row that has not "pk" key so the code just bombs.  I'm now looking for that key before we try to reference it.

### CODE REVIEW

**Comment by DrCherry** [comment]
Also noticed that these guys are mandatory.  We should update the example.

bot.whitelist = []
bot.blacklist = []

**Comment by DrCherry** [comment]
I just added it to the class so I think the over-ride will work so it'd be optional in the example.

**Comment by DrCherry** [comment]
So I got bot.like_timeline() working, bot.like_and_follow_your_feed_likers() works but seems like it only likes 3 pieces of media.

**Comment by ohld** [comment]
Thank you for your pull request. 
I've already fixed the issue about empty blacklist and whitelists (commit ed30586)

**Comment by ohld** [comment]
And please remove lots of printing in function. We don't need to print every media_id. We should try to print only errors and Main information

**Comment by DrCherry** [comment]
^^ Just kill my changes to the black/white lists and it'll merge just fine.

**Comment by DrCherry** [comment]
That should do it.

**Pull request merged**
