### PR TITLE
User can now set 'verbosity' variable to False to print less …

### PR DESCRIPTION
**Pull request by onkaraman**
With this branch users of this package can set `verbosity `to `False ` when initiaiting the `Bot` (default is `True`). When done, much less info like "Skipping" or "Writing user id to followed.txt" will be printed to the console.

The output will look _cleaner_ for those who prefer it.

### CODE REVIEW

**Comment by sudoguy** [comment]
Can you make function, where you can check verbosity state and print text? And replace all print() on this function. It's better than write "if bot.verbosity" before every print call

**Comment by onkaraman** [comment]
Sure. Will push it soon!

**Comment by onkaraman** [comment]
@sudoguy Pushed.

**Comment by sudoguy** [comment]
@onkaraman, good job! Thanks!

**Comment by ohld** [comment]
@onkaraman This version is not python3 compatible. You should use print function in a universe way. If you don't fix that issue, this commit will be reverted.

```File "/instabot/../../instabot/instabot/bot/bot_follow.py", line 16
    console_logger.print(self.verbosity, '\n\033[92m ===> FOLLOWED <==== user_id: %s \033[0m')
                       ^
SyntaxError: invalid syntax```

**Comment by sudoguy** [comment]
@ohld @onkaraman already fixed https://github.com/instagrambot/instabot/commit/fadbeea3eeb5438e1e90b0d2fc0d1bcddb130e51

**Pull request merged**
