### PR TITLE
autopost: made the caption readable from a possible description file replaced space sep with minus (-)

### PR DESCRIPTION
**Pull request by amstegraf**

### CODE REVIEW

**Comment by ohld** [comment]
Great Update! Can you please create also a wiki page with instructions on how to use this autopost script? Thanks.

**Comment by amstegraf** [comment]
> Great Update! Can you please create also a wiki page with instructions on how to use this autopost script? Thanks.

I've updated the REAMDE.md found in autopost folder

**Comment by ohld** [comment]
Sorry, but what was the point of renaming files to have dashes instead of spaces?

**Comment by amstegraf** [comment]
It's safer & easier to work with filepaths without spaces, less things to worry about. Much cleaner to use the image file name as an ID rather than a caption. And in the end it falls back to using the filename as a caption if anything before fails. So mainly because with this feature the filename's purpose has changed.

[Best Practices for File Naming](https://records-express.blogs.archives.gov/2017/08/22/best-practices-for-file-naming/)

**Comment by ohld** [comment]
Great! Thank you for your Pull Request!

**Pull request merged**
