### PR TITLE
added mute user options

### PR DESCRIPTION
**Pull request by ayush3298**
Added mute user options, the method takes two parameters, what to mute story and post

### CODE REVIEW

**Comment by ohld** [comment]
great commit! May I ask you please also to add tests to your new API endpoints? Thanks.

**Comment by ayush3298** [comment]
Sure I will try to, I don't know much about writing tests. Also, I was having some issue with insight endpoint, can you help me with that?

**Review by ohld — APPROVED** [review]

**Comment by ohld** [comment]
> Insight endpoint, can you help me with that?

No, but you can find another Instagram API repo who already implemented this API and become inspired with their solutions. And maybe add their code to our repo too.

**Comment by ayush3298** [comment]
I have the endpoints, also trying to use them. but that's not working

**Comment by efaria** [comment]
still not working ?

**Pull request merged**
