### PR TITLE
Added don't Follow function

### PR DESCRIPTION
**Pull request by thestation**

### CODE REVIEW

**Comment by ohld** [comment]
@sudoguy Check please.

**Comment by mwargan** [comment]
Hey! I tried your pull request but I'm getting an indentation error on line 63 (ultimate.py). I've removed one indentation to be inline with the line above it, but honestly am not sure if that'll effect the performance of the script.

**Comment by mwargan** [comment]
Also, it looks like job12 (uploading images) is not being called in the scheduler. Adding this line should help:
`schedule.every(1).days.at("21:28").do(run_threaded, job12)   #upload pics`

**Comment by thestation** [comment]
Hi mwargan!  
I will make sure to fix that first issue than. The only reason I am not calling job 12 is because I have the ultimate.py set to my preferences but I can change it. You should see a fix soon.
Thanks for the feedback!

**Comment by ohld** [comment]
@mwargan Can you please make a quick check again?

**Comment by ohld** [comment]
Thanks for this pull request. 
Next step is to improve the documentations in examples and in Readme Markdown files
.

**Comment by ermiyaeskandary** [comment]
@thestation @ohld 
`AttributeError: 'Bot' object has no attribute 'dont_follow'`

**Comment by thestation** [comment]
Can you please explain more? Dont_follow has no attribute because it is
just like a whitelist. So if you are running ultimate_schedule it will get
it everyone you follow and everyone that follows you everyday. I am trying
to work on a reload script function for ultimate schedule so it will keep
reloading the dontFollow.txt list everyday, instead of doing it manually.
Hopefully this answers your question!

**Pull request merged**
