### PR TITLE
Added media insight and story endpoints in API

### PR DESCRIPTION
**Pull request by ayush3298**
def get_user_reel(self, user_id):
        url = 'feed/user/{}/reel_media/'.format(user_id)
        return self.send_request(url)

    def get_user_stories(self, user_id):
        url = 'feed/user/{}/story/'.format(user_id)
        return self.send_request(url)

    def get_tv_suggestions(self):
        url = 'igtv/tv_guide/'
        return self.send_request(url)

    def get_media_insight(self, media_id):
        url = 'insights/media_organic_insights/{}/?ig_sig_key_version={}'.format(media_id, config.IG_SIG_KEY)
        return self.send_request(url)

### CODE REVIEW

**Comment by Ritchie001** [comment]
Does this mean the branch is merged?

And if so do i have to uninstall my instabot and reinstall the new one?

**Comment by remorses** [comment]
What is the difference between `get_user_reel` and `get_user_stories`?

**Comment by remorses** [comment]
I made some research and seems that the `get_user_reel` endpoint simply returns the same data of `get_user_stories` but inside a `reel` key and with added `broadcast` and `status` keys.
I paste here the general json structure of the responses:

### `get_user_reel` response
```
{
	broadcast {
		_
	}
	reel {
		id
		latest_reel_media
		expiring_at
		seen
		can_reply
		can_reshare
		reel_type
		user {
			pk
			username
			full_name
			is_private
			profile_pic_url
			profile_pic_id
			friendship_status {
				following
				followed_by
				blocking
				muting
				is_private
				incoming_request
				outgoing_request
				is_bestie
			}
			is_verified
		}
		items[9] {
			taken_at
			pk
			id
			device_timestamp
			media_type
			code
			client_cache_key
			filter_type
			image_versions2 {
				candidates[2] {
					width
					height
					url
				}
			}
			original_width
			original_height
			caption_position
			is_reel_media
			is_dash_eligible
			video_dash_manifest
			video_codec
			number_of_qualities
			video_versions[3] {
				type
				width
				height
				url
				id
			}
			has_audio
			video_duration
			user {
				pk
				username
				full_name
				is_private
				profile_pic_url
				profile_pic_id
				is_verified
				has_anonymous_profile_picture
				reel_auto_archive
				is_unpublished
				is_favorite
			}
			caption {
				_
			}
			caption_is_edited
			photo_of_you
			can_viewer_save
			organic_tracking_token
			expiring_at
			imported_taken_at
			can_reshare
			story_hashtags[1] {
				x
				y
				z
				width
				height
				rotation
				is_pinned
				is_hidden
				hashtag {
					name
					id
				}
			}
			supports_reel_reactions
			show_one_tap_fb_share_tooltip
			has_shared_to_fb
		}
		prefetch_count
		has_besties_media
		media_count
	}
	status
}
```
### `get_user_stories` response
```
{
	id
	latest_reel_media
	expiring_at
	seen
	can_reply
	can_reshare
	reel_type
	user {
		pk
		username
		full_name
		is_private
		profile_pic_url
		profile_pic_id
		friendship_status {
			following
			followed_by
			blocking
			muting
			is_private
			incoming_request
			outgoing_request
			is_bestie
		}
		is_verified
	}
	items[9] {
		taken_at
		pk
		id
		device_timestamp
		media_type
		code
		client_cache_key
		filter_type
		image_versions2 {
			candidates[2] {
				width
				height
				url
			}
		}
		original_width
		original_height
		caption_position
		is_reel_media
		is_dash_eligible
		video_dash_manifest
		video_codec
		number_of_qualities
		video_versions[3] {
			type
			width
			height
			url
			id
		}
		has_audio
		video_duration
		user {
			pk
			username
			full_name
			is_private
			profile_pic_url
			profile_pic_id
			is_verified
			has_anonymous_profile_picture
			reel_auto_archive
			is_unpublished
			is_favorite
		}
		caption {
			_
		}
		caption_is_edited
		photo_of_you
		can_viewer_save
		organic_tracking_token
		expiring_at
		imported_taken_at
		can_reshare
		story_hashtags[1] {
			x
			y
			z
			width
			height
			rotation
			is_pinned
			is_hidden
			hashtag {
				name
				id
			}
		}
		supports_reel_reactions
		show_one_tap_fb_share_tooltip
		has_shared_to_fb
	}
	prefetch_count
	has_besties_media
	media_count
	status
}
```
these json structures are made with [unmask-json](https://github.com/remorses/unmask-json)

**Review by remorses — APPROVED** [review]

**Comment by ohld** [comment]
@maxdevblock can you please check this? This looks nice.

**Comment by maxdevblock** [comment]
@remorses 
you mean the inverse, maybe a typo.

With `feed/user/{}/story/` called by `bot.api.get_user_stories` you get:
```
broadcast
status
reel
```

with `feed/user/{}/reel_media/` called by `bot.api.get_user_reel` you get the `reel` content itself
```
status
can_reply
expiring_at
reel_type
can_reshare
has_besties_media
latest_reel_media
media_count
prefetch_count
user
items
seen
id
```

**Comment by maxdevblock** [comment]
> @maxdevblock can you please check this? This looks nice.

Didn't check all new functions but yeah, good job @ayush3298 !!!

**Review by ohld — APPROVED** [review]

**Pull request merged**
