### PR TITLE
Add Support For Jupyter notebooks

### PR DESCRIPTION
**Pull request by llk23r**

### CODE REVIEW

**Comment by ohld** [comment]
Thanks for this PR! 

Also, I think it would be much cooler to read data from function params instead of `input()`.

**Review by ohld — APPROVED** [review]

**Comment by basnijholt** [comment]
LGTM!

**Comment by ohld** [comment]
I'm not sure that `examples/multi_script_CLI.py` script is still usable, but still thanks for the PR.

**Comment by llk23r** [comment]
> Thanks for this PR!
> 
> Also, I think it would be much cooler to read data from function params instead of `input()`.

@ohld  Could you elaborate further how do I go about doing that; especially for `instabot/api/prepare.py` ? 

The current implementation using the `sys.stdin.readline()` to read credentials fails on Jupyter Notebook.

TIA

**Comment by ohld** [comment]
The overall best approach is to read everything (including the credentials) is via environment variables.
``` python
import os
os.getenv(...)
```

Read more here: https://12factor.net/

**Comment by llk23r** [comment]
> Read more here: https://12factor.net/

Thanks for the link @ohld, I'll read up on it.

**Pull request merged**
