### PR TITLE
Improve Code Challenge handling: Replace spaces in code

### PR DESCRIPTION
**Pull request by fighterii**
As I found out, if you enter the code just as you receive it via SMS (e.g. "123 123") the code is not accepted. You have to enter the code without spaces. To make it more userfriendly in case some users enter the code just as they receive it, i remove spaces from the input.

### CODE REVIEW

**Review by bruvv — CHANGES_REQUESTED** [review]
`code = input("Insert code: ").replace(" ", "")`
There should be a space after the comma

**Review by bruvv — CHANGES_REQUESTED** [review]
You uploaded your pipfile which isn't needed ;)

**Comment by fighterii** [comment]
> 
> 
> You uploaded your pipfile which isn't needed ;)

Damnit, this git, travis thing is so frustrating to get right in the first time :D

**Comment by bruvv** [comment]
haha same!

**Comment by ohld** [comment]
hm. Why `pipfile.lock` is changed?

**Comment by fighterii** [comment]
> 
> 
> hm. Why `pipfile.lock` is changed?

Sorry, my fault. First i commited unintentionally some local changes, than i wanted to revert my fault and commited the delete of the whole file :D I now restored the old file from master again.

**Review by ohld — APPROVED** [review]

**Pull request merged**
