### PR TITLE
Config upgrades, add devices support.

### LINKED ISSUE #562: Update devices and headers to avoid 400 error or being banned
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [X] Updated to the latest version
- [X] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [X] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### For a *bug report*, you **must** include the Python version used, *code* that will reproduce the error, and the *error log/traceback*.

Paste the output of ``python -V`` here:
> Python 3.6.5

Code:
>Any request, mostly when liking.

Error/Debug Log:

```python
<Response [400]>
{'feedback_action': 'report_problem',
 'feedback_appeal_label': 'Report problem',
 'feedback_ignore_label': 'OK',
 'feedback_message': 'This action was blocked. Please try again later. We '
                     'restrict certain content and actions to protect our '
                     'community. Tell us if you think we made a mistake.',
 'feedback_title': 'Action Blocked',
 'feedback_url': 'repute/report_problem/instagram_like_add/',
 'message': 'feedback_required',
 'spam': True,
 'status': 'fail'}
```

---

### Describe your issue

After a few months using this project (mostly the API section) I went through multiple issues, from login challenges to spam detections, IP bans, timeouts... I was able to solve most of them thanks to the documentation, issues here and googleing a bit. 

My last issue has been being banned from liking from 5 of my 11 accounts I have in my bot. I have to say that I'm not using exactly this bot, but a custom made version, but is 100% based on this code and is also using the original `instabot.api` package, with just a couple of changes to make it Django compatible.

After 2 days debuging and trying with new proxies, servers, configurations and so on, I think I found a key part that was making the bot being detected as spam... I can see in `instabot.api.config.py` that the `DEVICE_SETTINGS` info is quite outdated, using old instagram api, android and release version. Also when making requests with `API.send_request()`, the current headers are

```python
self.session.headers.update({
            'Connection': 'close',
            'Accept': '*/*',
            'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
            'Cookie2': '$Version=1',
            'Accept-Language': 'en-US',
            'User-Agent': config.USER_AGENT
}
```
which are also not 100% complete.

Reading about the project, sources and more issues, I can see that two projects are named as sources:
- [Insatagram-API](https://github.com/mgp25/Instagram-API) - Php
- [instagram_private_api](https://github.com/ping/instagram_private_api) - Python

Both of them have been updated recently with new configurations and versions for the user agent and headers. I think it would be nice to:
- Be able to selecet device as seen in [Insatagram-API GoodDevices.php](https://github.com/mgp25/Instagram-API/blob/master/src/Devices/GoodDevices.php)
- Add more headers to be more "real" on the requests [instagram_private_api client.py](https://github.com/ping/instagram_private_api/blob/422d61f0a8cc9de3d5a0e78bcba53751c44e5d63/instagram_private_api/client.py#L375)

I suggest to have something like this on the config.py
```python
DEVICES = {
    'Samsung Galaxy S7': {
        'name': 'Samsung Galaxy S7',
        'instagram_version': '26.0.0.10.86',
        'android_version': 24,
        'android_release': '7.0',
        'manufacturer': 'samsung',
        'device': 'SM-G930F',
        'model': 'herolte',
        'cpu': 'samsungexynos8890',
    },
    'Huawei Mate 9 Pro': {
        'name': 'Huawei Mate 9 Pro',
        'instagram_version': '26.0.0.10.86',
        'android_version': 24,
        'android_release': '7.0',
        'manufacturer': 'HUAWEI',
        'device': 'LON-L29',
        'model': 'HWLON',
        'cpu': 'hi3660'
    }
}
DEVICE_SETTINGS = DEVICES['Samsung Galaxy S7']
USER_AGENT = 'Instagram {instagram_version} Android ({android_version}/{android_release}; 640dpi; 1440x2560; {manufacturer}; {device}; {model}; {cpu}; en_US)'.format(**DEVICE_SETTINGS)

# --- Requests variables
ACCEPT_LANGUAGE = 'en-US'
ACCEPT_ENCODING = 'gzip,deflate'
CONTENT_TYPE = 'application/x-www-form-urlencoded; charset=UTF-8'
X_FB_HTTP_Engine = 'Liger'
X_IG_Connection_Type = 'WIFI'
X_IG_Capabilities = '3brTBw=='  # = base64.b64encode(struct.pack('<i', 131316445)).decode('ascii')
IG_SIG_KEY = '99e16edcca71d7c1f3fd74d447f6281bd5253a623000a55ed0b60014467a53b1'
```

And update the `API.send_request()` with:
```python
self.session.headers.update({
            'Connection': 'Keep-Alive',
            'X-IG-Capabilities': config.X_IG_Capabilities,
            'X-IG-Connection-Type': config.X_IG_Connection_Type,
            'X-FB-HTTP-Engine': config.X_FB_HTTP_Engine,
            'Accept': '*/*',
            'Accept-Encoding': config.ACCEPT_ENCODING,
            'Accept-Language': config.ACCEPT_LANGUAGE,
            'Content-type': config.CONTENT_TYPE,
            'Cookie2': '$Version=1',
            'User-Agent': config.USER_AGENT
})
```

This way it will be easier and more flexible to update devices when we found new ones, and also easier to update the requests headers, so we can be up to date and avoid being banned easely. 

**In summary:**
These are the changes I made on the project to be able to have all my accounts online and working again:
- Logout from all accounts
- Update `DEVICE_SETTINGS` info in `config.py`
- Add new headers to `API.send_request()`
- Change Ips for **some** accounts (using proxies)
- Login again into all accounts

### PR DESCRIPTION
**Pull request by alberdonpi**
Clean config file and add devices file.
Add multiple devices settings.
Add new headers to request.
Move DEVICE_SETTINGS and USER_AGENT from api.config to API variables.
Add device support to Bot and API.
Fixes #562

### CODE REVIEW

**Comment by basnijholt** [comment]
Looks great!

You write that you took the variables from https://github.com/mgp25/Instagram-API/blob/master/src/Devices/GoodDevices.php however I see some differences in the `instagram_version`s between that page and the code you wrote. Is that on purpose or by accident?

**Review by sudoguy — APPROVED** [review]
Great job!

**Review by basnijholt — CHANGES_REQUESTED** [review]
Just the question I asked above.

**Comment by alberdonpi** [comment]
@basnijholt sorry forgot to mention that, on my research I used multiple repositories and just named that one as it was the more complete and from where I took the idea of multiple devices, but I took the most updated conf from [ping/instagram_private_api](https://github.com/ping/instagram_private_api/blob/422d61f0a8cc9de3d5a0e78bcba53751c44e5d63/instagram_private_api/constants.py#L12) as the last update was on Feb 7th vs March 2017 on the former one. I also use that device conf on my project ('samsung_galaxy_s7') and after a couple of weeks I can say it works good, hope that solve the doubts! :smiley:

**Review by basnijholt — APPROVED** [review]

**Comment by basnijholt** [comment]
Sounds good! Thanks again 🙇

**Pull request merged**
