### PR TITLE
Update the very old issue template and use the new bug report

### PR DESCRIPTION
**Pull request by bruvv**

### CODE REVIEW

**Comment by ohld** [comment]
same, please use CAPS LOCKED name (or check the examples in popular repos)

**Review by ohld — APPROVED** [review]

**Comment by bruvv** [comment]
@ohld it's not working I think you should enable it in settings too.

**Comment by bruvv** [comment]
@ohld it's not working I think you should enable it in settings too.

**Comment by ohld** [comment]
Somehow I couldn’t find the proper settings. Can you please guide me where are they and what exactly should I do

**Comment by bruvv** [comment]
If you grant me permission I can do it and perhaps help to close issues and stuff? Otherwise you can find it here:
Screenshot_20200110-084608
Click the green button and it should add 2 templates

**Pull request merged**
