### PR TITLE
Feedback protection

### PR DESCRIPTION
**Pull request by maxdevblock**
Added
`blocked_actions_protection`
to protect users from `feedback_required` with like and comment actions.

`bot.blocked_actions[key]` is updated to `True` when `feedback_required` is returned from `send_request`.
`bot.blocked_actions` is stored in `.checkpoint` and is reset within `reset_counters`.

Added tests too for `feedback_required` responses with like and comment action and test for comment with `status: ok`

### CODE REVIEW

**Comment by ohld** [comment]
Nice. Great job! Please fix conflicts and I'll merge this

**Comment by maxdevblock** [comment]
@ohld ok I'm on mobile now, will fix asap

**Review by ohld — DISMISSED** [review]

**Comment by ohld** [comment]
uff, suddenly check was failed.

**Comment by ayush3298** [comment]
Sometime instagram send feedback required message when the user has either turned off the action like comment, or there are some other reasons too.

**Comment by ayush3298** [comment]
`{'message': 'feedback_required', 'spam': True, 'feedback_title': 'Action Blocked', 'feedback_message': 'Based on previous use of this feature, your account has been temporarily blocked from taking this action. This block will expire on 2019-01-24. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.', 'feedback_url': 'repute/report_problem/user_restriction_LIKE_RESTRICT/', 'feedback_appeal_label': 'Tell us', 'feedback_ignore_label': 'OK', 'feedback_action': 'report_problem', 'status': 'fail'}```

This is what we get when instagram block us, we can use fliter like
if spam == True

**Comment by maxdevblock** [comment]
> `{'message': 'feedback_required', 'spam': True, 'feedback_title': 'Action Blocked', 'feedback_message': 'Based on previous use of this feature, your account has been temporarily blocked from taking this action. This block will expire on 2019-01-24. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.', 'feedback_url': 'repute/report_problem/user_restriction_LIKE_RESTRICT/', 'feedback_appeal_label': 'Tell us', 'feedback_ignore_label': 'OK', 'feedback_action': 'report_problem', 'status': 'fail'}```
> 
> This is what we get when instagram block us, we can use fliter like
> if spam == True

You're right, I'll work on it. Thanks.

**Comment by maxdevblock** [comment]
> `{'message': 'feedback_required', 'spam': True, 'feedback_title': 'Action Blocked', 'feedback_message': 'Based on previous use of this feature, your account has been temporarily blocked from taking this action. This block will expire on 2019-01-24. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.', 'feedback_url': 'repute/report_problem/user_restriction_LIKE_RESTRICT/', 'feedback_appeal_label': 'Tell us', 'feedback_ignore_label': 'OK', 'feedback_action': 'report_problem', 'status': 'fail'}```
> 
> This is what we get when instagram block us, we can use fliter like
> if spam == True

You're right but, as you said, you can receive `feedback_required` for many reasons, not only for spam. If you get `feedback_required` and you don't give up with that action, your account could be blocked or even deleted, even if the reason of `feedback_required` is not spam...
So, we may check if the reason of `feedback_required` is spam, but only to alert the user that instagram thinks he's spamming. Nevertheless when `feedback_required` is returned, it means that an action has been blocked (for spam or any other reason) and you must give up with it.
So, `blocked_action_protection` can protect the user, even if he's not spamming.

**Comment by maxdevblock** [comment]
@ohld I guess the branch is some commits behind the master, but I can't update or solve conflicts. Can you check please? Thanks

**Comment by ohld** [comment]
This is the error log from Travis - some test was failed. 
```
=================================== FAILURES ===================================
_____________________ TestBotGet.test_like_medias[medias0] _____________________
self = <tests.test_bot_like.TestBotGet object at 0x7f047f1afeb8>
patched_time_sleep = <MagicMock name='sleep' id='139657289395896'>
medias = [1234567890, 9876543210]
    @pytest.mark.parametrize('medias', [[1234567890, 9876543210]])
    @patch('time.sleep', return_value=None)
    def test_like_medias(self, patched_time_sleep, medias):
        self.bot._following = [1]
    
        for media in medias:
            TEST_PHOTO_ITEM['pk'] = media
            responses.add(
                responses.GET, "{api_url}media/{media_id}/info/".format(
                    api_url=API_URL, media_id=media),
                json={
                    "auto_load_more_enabled": True,
                    "num_results": 1,
                    "status": "ok",
                    "more_available": False,
                    "items": [TEST_PHOTO_ITEM]
                }, status=200)
    
            results = 2
            response_data = {
                "caption": TEST_CAPTION_ITEM,
                "caption_is_edited": False,
                "comment_count": 4,
                "comment_likes_enabled": True,
                "comments": [TEST_COMMENT_ITEM for _ in range(results)],
                "has_more_comments": False,
                "has_more_headload_comments": False,
                "media_header_display": "none",
                "preview_comments": [],
                "status": "ok"
            }
            responses.add(
                responses.GET, '{api_url}media/{media_id}/comments/?'.format(
                    api_url=API_URL, media_id=TEST_PHOTO_ITEM['pk']), json=response_data, status=200)
    
            response_data = {
                'status': 'ok',
                'user': TEST_USERNAME_INFO_ITEM
            }
            responses.add(
                responses.GET, '{api_url}users/{user_id}/info/'.format(
                    api_url=API_URL, user_id=TEST_PHOTO_ITEM['user']['pk']
                ), status=200, json=response_data)
    
            response_data = {
                'status': 'ok',
                'user': TEST_USERNAME_INFO_ITEM
            }
            responses.add(
                responses.GET, '{api_url}users/{user_id}/info/'.format(
                    api_url=API_URL, user_id=TEST_PHOTO_ITEM['user']['pk']
                ), status=200, json=response_data)
    
            responses.add(
                responses.POST, '{api_url}media/{media_id}/like/'.format(
                    api_url=API_URL, media_id=TEST_PHOTO_ITEM['pk']
                ), status=200, json={'status': 'ok'})
    
        broken_items = self.bot.like_medias(medias)
>       assert [] == broken_items
E       assert [] == [1234567890, 9876543210]
E         Right contains more items, first extra item: 1234567890
E         Use -v to get the full diff
tests/test_bot_like.py:539: AssertionError
---------------------------- Captured stderr setup -----------------------------
2019-01-24 17:29:52,317 - INFO - Instabot Started
------------------------------ Captured log setup ------------------------------
bot.py                     185 INFO     Instabot Started
----------------------------- Captured stdout call -----------------------------
Media ID error!
```

**Comment by maxdevblock** [comment]
@ohld error found and fixed...
`@responses.activate` missing before `def test_like_medias`

**Review by ohld — APPROVED** [review]

**Pull request merged**
