### PR TITLE
Upload photo resized and cropped

### PR DESCRIPTION
**Pull request by maxdevblock**
Edited def `upload_photo` and added def `resize_picture` in _api_photo.py_ to correctly resize, crop and convert pictures to fit instagram upload standards.
Both `exiftool` and `convert` (ver 7.x) are required on OS.
Example in _examples/photo_ folder with links to instructions how to install required tools.

### CODE REVIEW

**Comment by ghost** [comment]
I dont think this is a good direction. People will have to download external application just to repost a picture.

**Comment by maxdevblock** [comment]
> I dont think this is a good direction. People will have to download external application just to repost a picture.

Yes I know... maybe it's not the best solution, but it's the only one I found for now. And people have to use external tools still (say `ffmpeg`) to upload videos.

Maybe I could edit this pull request adding a default `convert=False` in def `upload_photo` in _api.py_ so people can choose setting to `convert=True` if they want the script to crop/resize/convert photos in case they've got the 3rd party requirement on their OS.

What do you think about it?

**Review by ohld — CHANGES_REQUESTED** [review]
Can you all universal taways to install all required libraries? Will this `POpen` work on windows machines? It is much better to use python packages instead of terminal CLIs. Please find corresponding lightweight python packages that have the same functionallity, add the into /photos/ folder’s requirements.txt and add a reminder in a /photos/Readme.md that additional packages have to be installed.

**Comment by maxdevblock** [comment]
I'm working on a totally different way using python modules only. I'll run tests next days and if everything is ok I'll closed this pull req and pull a new one.

**Comment by maxdevblock** [comment]
Closing pull request and pulling a new one with only python modules used to crop/resize/convert photos

**Pull request closed without merging**
