### PR TITLE
Specify additional options for upload_video/photo via options

### PR DESCRIPTION
**Pull request by adw0rd**
Specify additional options for upload_video/photo via options (.e.g. rename, rename_thumbnail, configure_timeout)

### CODE REVIEW

**Comment by ohld** [comment]
Thanks for your additions!

Since you are changing the function arguments, may I ask you please to add a docstring for the function? Because there are a lot of Instabot users that already use this method and it would be great to help them about new arguments.

**Comment by adw0rd** [comment]
@ohld okay, I'll add docstrings on the week 👍

**Comment by adw0rd** [comment]
I fixed some problems (after long testing) and wrote docstrings for functions with "options" param

**Comment by ohld** [comment]
There are conflicts of your pull request and the existed code: look above on this page. Please resolve them, I can’t merge now.

**Comment by adw0rd** [comment]
@ohld I solved the conflict

**Review by ohld — APPROVED** [review]

**Comment by ohld** [comment]
Thanks! Great pull request!

**Pull request merged**
