### PR TITLE
Extend logging

### PR DESCRIPTION
**Pull request by fighterii**
I changed default loglevels to console: INFO and file: DEBUG. I think this i more convenient, users from console usually are just interested in INFO and above, while users looking for debug infos will dig more into it and therefore take a look at the log files.

I added the Instabot version to the Logger and changed the Formatter for the File logger to include the calling module and the logger name with the instabot version

I also added a debug call when initialising the bot to indicate from where the API file is imported as well some debug logging for loading/saving checkpoint information.

### CODE REVIEW

**Comment by fighterii** [comment]
This PR could also fix #1239 , or at least give a better understanding on how the exception is raised

**Comment by bruvv** [comment]
Thanks there is a conflict with the requirements file. Can you fix that?

**Comment by fighterii** [comment]
@bruvv : Unfortunately not. The development base says `schedule=>=0.6.0` which is invalid syntax. Because of this all CI builds fail:

`error in instabot setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'=>=0.6.0'"
`

my fail has corrected syntax, but this is somehow a conflict. So my version should be right, and i can not edit this conflict---

**Comment by bruvv** [comment]
@fighterii I just noticed the build is not passing:
https://travis-ci.org/instagrambot/instabot/jobs/639554416?utm_medium=notification&utm_source=github_status
```
E   ImportError: cannot import name Bot
```

Can you fix this please so I can merge it to master?

**Comment by fighterii** [comment]
@bruvv: there is also 

ImportError: cannot import name utils

Which definitely wasn't changed. Maybe there is something else wrong...

**Pull request merged**
