### PR TITLE
Implement previously followed user check in bot.follow()

### PR DESCRIPTION
**Pull request by lorenzonodari**
I noticed that when using the bot.follow() function, the followed.txt file is ignored, and users are followed regardless of wheter they were previously followed or not. Since i noticed that the file is checked in the bot.follow_users() function, i thought that the same behavior would be desirable for the former function as well. I'm fairly new to the project though, so let me know if i'm missing some reasons not to implement this behavior or mistakes i have made when implementing the feature!

### CODE REVIEW

**Comment by basnijholt** [comment]
Thanks for the contribution.

I think the check is good, however, it probably belongs in a different file: https://github.com/instagrambot/instabot/blob/master/instabot/bot/bot_filter.py#L160

**Comment by lorenzonodari** [comment]
Thank you @basnijholt for the great project! I will immediately procede to implement the feature in the check_user function!

**Comment by lorenzonodari** [comment]
As requested, i added the feature to the check_user function instead of the follow function. Due to this reason, i also removed the same check in the bot.follow_users() function, as with this change it became redundant. In order not to potentially break or modify previous code depending on the old behavior, I added the filtering configuration to the bot constuctor, defaulting to False.

**Comment by basnijholt** [comment]
Great! 

I don't think this was working though, I've added 4b371a1.

Could you test whether it actually works? :)

**Comment by lorenzonodari** [comment]
Ok, i tested the code and now it is working! In the commits I added i did not to much: fixed 2 minor errors and corrected a log message which i noticed was quite misleading. Let me know if everything is good!

**Review by basnijholt — APPROVED** [review]
LGTM

**Comment by basnijholt** [comment]
Thanks a lot!

**Comment by kintaro1981** [comment]
In my case `follow_user_followers.py` continue co re-follow unfollowed users that are already in followed.txt. At the beginning it filter only skipped.txt users.

```
Going to follow 10483 users.

After filtering `skipped.txt`, 9446 user_ids left to follow.
``` 

(my instabot is updated)

I can see that it's happening because the default behavior is "false", right?

**Comment by kintaro1981** [comment]
Yes, I set to True and now it works.

I added this comment to the commit: https://github.com/instagrambot/instabot/commit/f80b8104b64a20091be96f16b151ca7505043754#r29882931

**Pull request merged**
