### PR TITLE
adding personal Database files for each Instagram accounts 

### PR DESCRIPTION
**Pull request by a13sha**

### CODE REVIEW

**Comment by ohld** [comment]
Please fix travis ci errors and I'll merge your pull request, good job!

**Comment by sudoguy** [comment]
I think, for better backward compatibility, by default need to set "whitelist.txt", "blacklist.txt", etc.

**Comment by a13sha** [comment]
> I think, for better backward compatibility, by default need to set "whitelist.txt", "blacklist.txt", etc.

**Comment by a13sha** [comment]
ok i'll try for both

**Pull request closed without merging**
