### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by ohld**

### CODE REVIEW

**Comment by ohld** [comment]
@bruvv take a look at what was automatically generated

**Comment by bruvv** [comment]
Thanks, looks like there is a extra submap added. perhapse if I change the map of the other templates they get used? I still cannot edit the settings tho.

**Review by bruvv — APPROVED** [review]

**Comment by bruvv** [comment]
Is there a way we can communicate without posting comments here :) ? If you can give me more editing rights (and perhaps merging rights) I can speed up the developement and clean the bot.
I am also think about removing all the branches and create 1 new: development and leave the master as is. And only push a new version in the master once we merge from developement. All those tiny updates are not worth it in my opinion.

**Comment by ohld** [comment]
@bruvv you can reach me on Telegram https://t.me/okhlopkov

I don't think that your development branch would help a lot, we don't have any active development right now. Right now any fixes and enhancement would be awesome.

**Pull request merged**
