### PR TITLE
fixed wrong endpoint

### PR DESCRIPTION
**Pull request by Spixmaster**
I also wrote an Instagram API but in C++ which you can see as it is open source too. When copying the endpoints from other repositories I recognized that it seems to me that the concerned endpoint in this pull request seems to cause problems. In my case the Instagram servers returned an error. I think it was status code 301 with no response body but I cannot assure that but I think it was that.

I assume that you copied from mpg25/Instagram-API and he does the same: https://github.com/mgp25/Instagram-API/blob/master/src/Request/People.php (line 128)

I tried out ping's endpoint with query string which worked for me: https://github.com/ping/instagram_private_api/blob/0fda0369ac02bc03d56f5f3f99bc9de2cc25ffaa/instagram_private_api/endpoints/misc.py#L77

It is your decision: For me your and mpg25's solution did not work.

PS: How did you manage to get Instagram's endpoints?! It is such a torture to do that. I tried it for like 3 week with every possible solution I found on the Internet and nothing worked. I described what I did in my wiki if you are interested: https://github.com/Spixmaster/instagram-private-api/wiki

### CODE REVIEW

**Comment by Spixmaster** [comment]
In general, can forks be deleted after a successful merge?

**Comment by bruvv** [comment]
Yes and thanks will look into your pr asap

**Comment by bruvv** [comment]
First thing I noticed, you pulled against branch master. Can you do that to developement :) ?

**Comment by Spixmaster** [comment]
> First thing I noticed, you pulled against branch master. Can you do that to developement :) ?

Done.

**Comment by bruvv** [comment]
Thanks, merged!

I agree on the endpoints, @ohld did rebase it a few months ago with some aditions from different source including his own. It is not my expertise part too so I cannot reply on that much. Last link you posted: https://plainsec.org/how-to-bypass-instagram-ssl-pinning-on-android-v78/

**Comment by Spixmaster** [comment]
> Thanks, merged!
> 
> I agree on the endpoints, @ohld did rebase it a few months ago with some aditions from different source including his own. It is not my expertise part too so I cannot reply on that much. Last link you posted: https://plainsec.org/how-to-bypass-instagram-ssl-pinning-on-android-v78/

Thank you very much first for your trust in me concerning the pull request and for the kind answer concerning sniffing Instagram's http requests. It is so awful to try it and so frustrating.

Unfortunately, I tried every method despite that blog post but now I will try it out.

Thank you very much. I appreciate the developing community very much. They helped me out so many times.

I tried the instagram api from ping, LevPasha and this is definitely the best one.

Have a nice day.

**Pull request merged**
