### PR TITLE
fix video not upload

### PR DESCRIPTION
**Pull request by AKwoKWH**
**What this PR does / why we need it**:
There was an additional return in the function, which the 2nd one never being fired.

**Which issue(s) this PR fixes**:

Fixes # https://github.com/instagrambot/instabot/issues/1379

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g. usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by kushpvo** [comment]
How can I test this on my local machine?

**Comment by ohld** [comment]
Loking good to me @bruvv, please merge to Master

**Comment by kushpvo** [comment]
Would would be added to pip updates?

**Comment by ohld** [comment]
@kushpvo yep, After merging to master it will be automatically uploaded to pip

**Pull request merged**
