### PR TITLE
WIP: automatically create __version__

### PR DESCRIPTION
**Pull request by basnijholt**

### CODE REVIEW

**Comment by basnijholt** [comment]
The `__version__` will now always be correct and have the format described by pep440.

For example right now:
```
instabot.__version__
Out[2]: '0.4.2.dev4+gf710535.dirty
```

This tells us it's 4 commits after 0.4.2 and at commit f710535, the dirty means I have uncommited changes. 

This way we can always tell which version a user is using. It happened a couple of times already over the last few days that someone claims they are using a certain version, while in reality, they are not.

**Comment by ohld** [comment]
Very nice commit! 
Please fix CI errors and I'll approved that

**Comment by ohld** [comment]
@basnijholt Hi, what is the current progress on that PR?

**Comment by basnijholt** [comment]
Nothing

**Pull request closed without merging**
