### PR TITLE
Created InstagramBot Terms Of Service

### PR DESCRIPTION
**Pull request by order4adwriter**
check out the file here via this link. https://www.dropbox.com/s/78ja2rgsokgkzq4/InstagramBot%20TOS.docx?dl=0

Please merge immediately.

Thanks.

### CODE REVIEW

**Comment by basnijholt** [comment]
Thanks. But why do you think this is needed?

**Comment by basnijholt** [comment]
You make it sound as if the developers gain access to your account details, which is not the case.

**Comment by ohld** [comment]
@order4adwriter Can you please give us any example of open source project that uses this types of documents?

**Comment by order4adwriter** [comment]
Hello @ohld and Everyone,

Of the top of my head I'd say Tensorflow, Invoice Ninja, Flutter, Linode,....  Heck even the paid versions of every major Instagram -based bots out there all have a Privacy Policy..... every serious app, website or business entity needs one on their website.

@basnijholt , I'm sorry if I sounded that way but that was not my intention. I know the bot cannot do that.. .but most people out there may not know this or completely understand how the bot works. 

But in all honesty, you'll agree with me that having one serves a dual purpose of assuring your end  users of  the sincerity of your intentions in creating this bot as well, thus encouraging them to use  and spread the word about Instabot, ...  and to also offer some form of indemnity for you guys ...just in case some unforeseen circumstances occur.

All I'm saying is that it is a lot more confidence-boosting to potential users if they see a privacy policy  for Instabot on the website...than seeing nothing at all.

Hope this helps.

**Pull request closed without merging**
