### PR TITLE
Bugfix set_proxy after each send_request, not only for login

### PR DESCRIPTION
**Pull request by adw0rd**
Now set_proxy is called upon login, requests to the login pass without a proxy, because of this, Instagram does not allow access to the login

This fix will allow you to set the proxy at beginning and not be blocked by instagram

### CODE REVIEW

**Comment by ohld** [comment]
Many thanks! May I ask you to fix Travis-CI issues - and I'll merge

**Comment by adw0rd** [comment]
@ohld I did not notice an error, now I fixed it

**Comment by adw0rd** [comment]
I will continue to be more attentive

**Review by ohld — APPROVED** [review]

**Comment by ohld** [comment]
Great PR! Thanks!

**Pull request merged**
