### PR TITLE
Create download_users_videos.py

### PR DESCRIPTION
**Pull request by steffanjensen**

### CODE REVIEW

**Comment by ohld** [comment]
@basnijholt please use this PR to demonstrate and explain how to use your pre-commit stuff.

**Comment by basnijholt** [comment]
Sure, @reliefs needs to do `pip install pre-commit` to install the package.

Then `pre-commit install` and `pre-commit run --all` to run it on the existing code.

The next commits after `pre-commit install` has been done (once ever) then it will do it automatically.

**Comment by basnijholt** [comment]
If it doesn't work I can also fix it ;)

**Comment by reliefs** [comment]
lol no way i am doing that, but good luck :)

**Comment by basnijholt** [comment]
It would have taken like 1 minute?

**Comment by ohld** [comment]
@basnijholt see - no one is familiar with this thing. This is something strange and unexpected for me also - why should I install some software to commit to the project? 

@basnijholt Please revert your "pre-commit" stuff again - this ruins all open-source experience. @sudoguy please, don't merge PR with pre-commit stuff anymore without the discussion all prox and cons.

**Comment by basnijholt** [comment]
@ohld, it's exactly the same as what there was before.

There are just some other tests now.

> no one is familiar with this thing

Your sample size is 1? This is is nearly every serious Python package nowadays.

**Comment by ohld** [comment]
Can you please link some examples of projects which use this pre-commit thing? Because I don’t know any. 

For me it is really sad that you have to run some other program to commit the code. I would like to see the code style errors and learn instead of all this magic

**Comment by basnijholt** [comment]
Just some example from a few of the most popular (top 10) Python packages:

* https://github.com/pallets/flask/blob/master/.pre-commit-config.yaml
* https://github.com/home-assistant/home-assistant/blob/dev/.pre-commit-config.yaml
* https://github.com/pandas-dev/pandas/blob/master/.pre-commit-config.yaml

**Comment by reliefs** [comment]
For me personally I do not always use a device which has python/git/pip installed to edit the code.

**Comment by reliefs** [comment]
This update make users unable to commit directly from github.

**Pull request closed without merging**
