### PR TITLE
Randmise some numbers to prevent block

### PR DESCRIPTION
**Pull request by bruvv**

### CODE REVIEW

**Comment by ohld** [comment]
Did it help you to prevent from bans or you just suggest that this might help?

**Comment by bruvv** [comment]
Its a suggestion that this might help. I do know that instagram is doing more and more to prevent bots. And with these high numbers its more likely people will get blocked.

People can always override them if they need to. but if everyone is running with these easly spotted high numbers instagram can focus more on our bot and block that in general. That is the filosofy behind it

This is also a good suggestion: https://github.com/instagrambot/instabot/issues/1194

**Comment by fighterii** [comment]
@bruvv: As far as i understood you just changed the default values to more "odd" values.

What about using random.randint with a useful range?
For example:
```like_delay=random.randint(7,15),```
instead of
```like_delay=39,```

I guess performance is not the limiting factor if we use like 15-20 randint calls in the constructor instead of fixed values. And so each created bot instance is truly individual instead of just all new bot instances are now using an other fixed value. I suggest that this might be even better for instagram to not detected our bots.

**Comment by bruvv** [comment]
@fighterii I have no idea why I didn't do that lol thanks for the headsup

**Comment by ohld** [comment]
Great. Again, please fix Travis Issues and I'll merge. Thanks!

**Comment by bruvv** [comment]
Hahah stupid travis, always fighting with it. It's pretty strict ;)

**Comment by ohld** [comment]
You can try to use `pre-commit`

needs to do `pip install pre-commit` to install the package.

Then `pre-commit install` and `pre-commit run --all` to run it on the existing code.

The next commits after `pre-commit install` have been done (once ever) then it will do it automatically.

**Comment by bruvv** [comment]
Thanks, It started as some simple edits on github itself that, tbh, I didn't even test. Since there is much to be improve I will start doing it locally from now on. Will fork, and edit from there and do PR.s in that way

**Comment by ohld** [comment]
randint and randrange is almost the same:

https://docs.python.org/3/library/random.html#random.randrange

**Comment by bruvv** [comment]
@ohld little help with these last errors? I installed pre-commit, ran it and all works just fine: 
image
But when travis is doing it, it isn't passing the test.

Could it be that:
https://github.com/instagrambot/instabot/blob/master/tests/test_variables.py#L203
This photo trows an error:
`URL signature expired`
https://scontent-amt2-1.cdninstagram.com/vp/9ef94dbfea2b8cdb2ba5c9b45f1945fd/5AEFE328/t51.2885-15/e15/11137637_1567371843535625_96536034_n.jpg?ig_cache_key=MTIzNA%3D%3D.2

**Comment by fighterii** [comment]
@bruvv:
I think tests are getting more complicated with this change.
For example, if i check the travis build results:

```
INFO     [instabot_140343133661560]:bot_filter.py:9 Received 4 medias.
INFO     [instabot_140343133661560]:bot_filter.py:20 After filtration 0 medias left.
```
and the expected result:
```
>       assert len(medias) == results - expect_filtered
E       assert 0 == (4 - 3)
E        +  where 0 = len([])
```
because of randomised filter settings the checks sometimes will fail randomly.
I think best practice would be to use the old, default vals in the tests to initiate the bot instances.

**Comment by bruvv** [comment]
@fighterii you are right indeed, I thought it had to do with the image not being found but it looks like some where there is a misscommunication in the build. Do you know how to adjust the build so the numbers get hard coded in it?

**Comment by fighterii** [comment]
@bruvv 

I would take a look at tests/test_bot.py

As far as i understand all tests use the TestBot class as BaseClass for their tests. In line 20 the bot is created with:

```self.bot = Bot()```

I guess the best would be to pass all arguments that you like to randomise here with there old default values, for example:

```
        self.bot = Bot(
            max_likes_to_like=100,
            min_likes_to_like=20,
        )
```

**Comment by bruvv** [comment]
Good spot, let's see what travis thinks about it ;)

**Comment by bruvv** [comment]
That did it! Great minds think alike thanks for the spot @fighterii 
@ohld save to merge :) ?

**Review by ohld — APPROVED** [review]

**Comment by ohld** [comment]
merged! thanks!

**Pull request merged**
