### PR TITLE
update get_link_from_media_id()

### PR DESCRIPTION
**Pull request by negswell**
* fetching media ids is sometimes resulting in user id being appended to it using "_"
added fix for it 
*media_id, char = int(media_id) // 64, int(media_id) % 64
added int conversion as media_id in char form will give type error when divided by int value .

### CODE REVIEW

**Comment by ohld** [comment]
Great contribution! Please fix all Travis-CI codestyle issues and I'll merge it!

**Comment by bruvv** [comment]
This is indeed a bug and i will try and fix this soon. @ohld can you close this because of my PR: https://github.com/instagrambot/instabot/pull/1193

**Comment by untitled3000** [comment]
@negswell I'm getting the media_id by calling this function - get_media_id_from_link()

By inferring that the variable is a string, your change broke my code. Just FYI

**Comment by bruvv** [comment]
What code did you use?

**Comment by untitled3000** [comment]
Basically, I created a submit form that takes in an instagram link. I process the link and convert it to a media_id via get_media_id_from_link(). I then pass the media_id to a function that returns several attributes of the post. In this function, I also return the instagram link via get_link_from_media_id() (I know it's redundant, but it should still work). 

When I printed out the error, i got - 'int' object has no attribute 'find'

I reverted the get_link_from_media_id() function to before this update, which solved my problem.

**Comment by bruvv** [comment]
That's weird since the media is should always be a int object. Can you post your script as an issue and include the precise error message ? Inc the link too that your using. Than I'll debug the code.

**Comment by untitled3000** [comment]
Sounds good. I'll strip the code out and post when I have some extra time.

**Pull request closed without merging**
