### PR TITLE
print full error msg to handle response manually when there is error

### PR DESCRIPTION
**Pull request by AKwoKWH**
Changes:

1) add error msg details of "api_path" when challenge req
2) update the print format for "feedback_required"

### CODE REVIEW

**Comment by AKwoKWH** [comment]
Updated to print the full Json msg when there is error
This is for better debug when there are error when sending request to instagram.

seem instagram start blocking the bot  =(

**Comment by ohld** [comment]
please read the comments that I've left

**Comment by AKwoKWH** [comment]
> please read the comments that I've left

Hi @ohld 
Sorry, pretty new to github, where I can see your comments?

**Comment by ohld** [comment]
Just in this thread - scroll above.

**Comment by AKwoKWH** [comment]
I cant find it? @ohld 
are we in the same page?
image

**Comment by ohld** [comment]
go to 'files changed' above

**Review by AKwoKWH — COMMENTED** [review]
Test

**Comment by AKwoKWH** [comment]
@ohld 
my screen in "files changed" Tab
screencapture-github-instagrambot-instabot-pull-934-files-2019-06-23-01_01_19

**Pull request closed without merging**
