### PR TITLE
Add 'file' class

### PR DESCRIPTION
**Pull request by basnijholt**
This class can be used extensively in the `examples`.

### CODE REVIEW

**Comment by basnijholt** [comment]
@sudoguy and @ohld what do you guys think?

**Review by sudoguy — APPROVED** [review]
I think it's a good idea

**Comment by simongomez95** [comment]
,

On Apr 22, 2018 1:32 AM, "Evgeny Kemerov" <notifications@github.com> wrote:

Merged #504 <https://github.com/instagrambot/instabot/pull/504>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/instagrambot/instabot/pull/504#event-1587738735>, or mute
the thread

**Comment by ohld** [comment]
AWESOME GUYS!

**Pull request merged**
