### PR TITLE
Added BotState and BotCache singleton.

### PR DESCRIPTION
**Pull request by gioelecrispo**
They are intended to be shared between more instabot instances to solve the concurrency read/write problem in api.last_json when more tasks are run in threading mode.
When you have to run more task in parallel (threading mode) you have to create one instance of instabot for each task, so that different API instances are create and each API instance reads its own last_json variable.

### CODE REVIEW

**Comment by ohld** [comment]
Great PR! Can you please fix all Travis-CI issues to make your PR pass all the tests

**Comment by steffanjensen** [comment]
I have seen when threading user x sometimes gets user y logfiles and so on.. This will fix that or ?

**Comment by gioelecrispo** [comment]
No, it handles only the concurrency problem on API variables

**Comment by ohld** [comment]
Thank you for the fixes. But sadly Travis still arguing.

**Comment by yevyapan** [comment]
İ want start instagrambot. How to start? Please step by step write or any detail web site? Thanks 


Sent from Yahoo Mail for iPhone


On Pazartesi, Kasım 11, 2019, 12:26 ÖS, Daniil Okhlopkov <notifications@github.com> wrote:


Great PR! Can you please fix all Travis-CI issues to make your PR pass all the tests

**Review by ohld — APPROVED** [review]

**Comment by ohld** [comment]
Great pull request! Thanks!

**Pull request merged**
