### PR TITLE
Add 'get_messages' method that returns your inbox's messages, closes #495

### LINKED ISSUE #495: Retrieve messages
## Please follow the guide below

- Issues submitted without this template format will be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [x] Updated to the latest version
- [x] Read the [README](https://github.com/instagrambot/instabot/blob/master/README.md) and [docs](https://github.com/instagrambot/instabot/tree/master/docs)
- [x] [Searched](https://github.com/instagrambot/instabot/search?type=Issues) the bugtracker for similar issues including **closed** ones

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other
---

### Describe your issue

Hello, thanks for the project! Would it be possible to retrieve user messages? Right now we only have the possibility to send messages, but we can't understand if the person actually has replied to the message.

Maybe this your line could be helpful:

https://github.com/instagrambot/instabot/blob/97465a71615c39544d037bca670b5eb4fc8b02c1/instabot/api/api.py#L317

### PR DESCRIPTION
**Pull request by basnijholt**
This closes issue #495.

Adds a method `bot.get_messages`.

### CODE REVIEW

**Review by ohld — APPROVED** [review]

**Comment by Volodichev** [comment]
Does it work now without error like "Your Instagram app is out of date. Update it now to use Direct."?

**Comment by 733amir** [comment]
It seems it is not working.
@Volodichev I get that message you mentioned.

Any solution?

**Comment by ohld** [comment]
@733amir 
Can you please describe how to reproduce this error. That will help to fix this@basnijholt

**Comment by ohld** [comment]
@733amir
Can you please describe how to reproduce this error. That will help to fix this @basnijholt

**Comment by 733amir** [comment]
Running the following code will reproduce it for me:

```python
from instabot import Bot


userpass = ["username", "password"]

bot = Bot()
bot.login(username=userpass[0], password=userpass[1])

print(bot.get_messages())
```

Above code produce following output:
```
Cookie file `cookie.txt` not found
2018-09-18 09:04:33,571 - INFO - Instabot Started
2018-09-18 09:04:36,064 - INFO - Logged-in successfully as 'username'!
2018-09-18 09:04:36,065 - INFO - Saved cookie!
{'inbox': {}, 'megaphone': {'generic_megaphone': {'type': 'deprecate_raven_tray', 'title': 'Update Your App to Use Direct', 'message': 'Your Instagram app is out of date. Update it now to use Direct.', 'dismissible': False, 'icon': None, 'buttons': [{'text': 'Update', 'style': 'confirm', 'url': 'https://play.google.com/store/apps/details?id=com.instagram.android'}], 'megaphone_version': 'v1', 'button_layout': 'vertical', 'action_info': {}, 'button_location': 'bottom', 'uuid': '2dd5a93b63024eb3a8aa9a3089e258a6'}}, 'status': 'ok'}
2018-09-18 09:04:37,705 - INFO - Bot stopped. Worked: 0:00:04.134899
2018-09-18 09:04:37,706 - INFO - Total requests: 4
```

**Comment by 733amir** [comment]
@ohld Now the error is gone but my inbox is always empty. How can I fix that?

**Comment by ohld** [comment]
I don't know :(

**Comment by Volodichev** [comment]
Thanks to toster.ru! We need to change version of instagram in USER_AGENT (Ex.: 10.50.0) 

> It seems it is not working.
> @Volodichev I get that message you mentioned.
> 
> Any solution?

**Pull request merged**
