### PR TITLE
add user tag

### PR DESCRIPTION
**Pull request by jerryan9999**
**What this PR does / why we need it**:
add user tag when post photo
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: None

```release-note

```

**Additional documentation e.g. usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by bruvv** [comment]
Why close it?

**Comment by jerryan9999** [comment]
@bruvv  reopened

**Comment by bruvv** [comment]
please fix the build issues.

**Comment by bruvv** [comment]
Again reminder. Fix the build errors please

**Review by ohld — APPROVED** [review]

**Pull request merged**
