### PR TITLE
Made the project PEP8 compliant

### PR DESCRIPTION
**Pull request by jontymorris**
I'm on a mission to make all the files 100% PEP8 compliant.

``bot.py `` was pretty good already, but had a dozen or so lines that exceeded the recommended 80 column length. I went ahead and shortened these down, but I'm on the fence about some of them.

I also made Travis check the project for PEP8 compliance. However, some files are uncompliant so Travis will say there's a problem.

What do you guys think about this?

### CODE REVIEW

**Comment by jontymorris** [comment]
There are a remaining 411 instances of code not complying with the PEP8 guidelines. Until these are fixed, Travis will fail the checks.

God dammit. I'll fix these right away!

**Comment by jontymorris** [comment]
A bottle of coke later, the project is now PEP8 compliant!

**Comment by ohld** [comment]
Hi! Thanks for contribution. Can you also please fix our current Travis-CI config to teach him to test PEP-8 compliment of all future pul requests. Thanks.

**Comment by ohld** [comment]
We need to make sure that all future commits will be PEP8 compliant.

**Comment by jontymorris** [comment]
Already done! Once merged, Travis will fail any future pull request that isn't PEP8 compliant. See commit 1ae8c4d229b82cd4d1cc6df403507ad1733f9682 for more details.

**Comment by ohld** [comment]
Thanks! Really cool!

**Review by ohld — APPROVED** [review]

**Pull request merged**
