### PR TITLE
Save users' followers into file example

### LINKED ISSUE #505: Save user followers into a file example
Hi guys! I'd like to know if it's possible to add an example: **save user followers into a file**, it would be very useful for large number of users.

### PR DESCRIPTION
**Pull request by ofou**
I wanted to fix #505, I think it's really useful for large numbers of followers. I also added the "save users following into file" example. I'm not sure if the best way to do it, but it worked for me at least. :smile:

### CODE REVIEW

**Comment by ohld** [comment]
Wow, guys, @basnijholt @sudoguy, I think this is great!

**Comment by basnijholt** [comment]
Yes looks good! I made a very small change though, using `utils.file`.

**Review by basnijholt — COMMENTED** [review]
LGTM

**Review by basnijholt — DISMISSED** [review]

**Review by sudoguy — APPROVED** [review]

**Comment by sudoguy** [comment]
Great job, guys!
@ofou @basnijholt

**Pull request merged**
