### PR TITLE
'download video' as bot method

### PR DESCRIPTION
**Pull request by alexshavelev44**

### CODE REVIEW

**Comment by ohld** [comment]
Great! Thanks for the pull request!
Can you please fix the Travis-CI code style issues and I'll merge your code.

**Comment by alexshavelev44** [comment]
@ohld fixed import. but now am confused what to do with codecov

**Comment by alexshavelev44** [comment]
also, add download carousels videos. previously bot just crashes

**Review by ohld — APPROVED** [review]

**Comment by ohld** [comment]
Thanks for your work!

**Pull request merged**
