### PR TITLE
fix(login flow): remove return feedback_required

### PR DESCRIPTION
**Pull request by flaviohenriqu**
Returning the required feedback string causes the login stream not to verify
`checkpoint_challenge_required` on line 274 of `instabot/api/api.py`
Screenshot 2019-10-11 at 20 11 07

### CODE REVIEW

**Comment by ohld** [comment]
hmm, but on line 274 we check the `last_json`, not the return value of the function.

**Comment by ohld** [comment]
Please, help me to understand why this is important.

**Comment by flaviohenriqu** [comment]
> Please, help me to understand why this is important.

@ohld Since `send_request` is returning a string `feedback_required` it will not reach the condition of line 274, it will always get the first condition of line 266 wrong.

**Review by ohld — APPROVED** [review]

**Comment by ohld** [comment]
Then I'd suggest to replace it with `return False` instead to make this login explicit.

**Review by ohld — CHANGES_REQUESTED** [review]
Make `return False`

**Comment by flaviohenriqu** [comment]
> Make `return False`
@ohld 
But If `return False` the `last_json` will not be filled.

Just removing this line in the `send_request` code sequence will make `return False`.
Screenshot 2019-10-14 at 10 25 41

**Comment by ohld** [comment]
thanks

**Pull request merged**
